Allow scout to double jump when bhoping
8dcc/tf2-cheat pull request #5
Opened 2023-12-09 11:43 UTC by nepcat

2023-12-10 22:25 UTC, 8dcc commented
Just as a side note, on Nov 12, 2023 I tried adding this but was very buggy:


https://github.com/8dcc/tf2-cheat/assets/29655971/646ea12f-a6e9-46fa-bebf-bb63176d8d46

Now I just realized that it was probably fixed in commit d9fcfb5ff2ce9fba9e6aee73fc56a4bfd6a79ac3

2023-12-17 18:49 UTC, nepcat commented
Is there anything wrong with my pull request?

2023-12-17 19:16 UTC, 8dcc commented
> Is there anything wrong with my pull request?

Yes, I made a review explaining that line 75 should remain the same. I can make the changes if you want, I was waiting for you.

**EDIT**: I just realized I can only see the review if I am logged in, not sure why.

2023-12-17 19:17 UTC, 8dcc requested changes

2023-12-17 19:20 UTC, nepcat commented on src/features/movement.c
> +    if (!is_on_ground) {
Done

2023-12-17 19:48 UTC, 8dcc approved these changes

2023-12-17 19:48 UTC, merged

2023-12-17 19:48 UTC, 8dcc commented
Thank you for your contribution!